# Generated by Django 2.2.4 on 2021-04-27 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symb', models.CharField(max_length=5)),
                ('comp_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='stocks', to='login_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sold_price', models.DecimalField(decimal_places=2, default=None, max_digits=15)),
                ('gain_loss', models.DecimalField(decimal_places=2, default=None, max_digits=15)),
                ('percent_gain', models.DecimalField(decimal_places=2, default=None, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks', to='stocks_app.Stock')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks', to='login_app.User')),
            ],
        ),
    ]
