# Generated by Django 2.2.4 on 2021-04-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_stock',
            old_name='users',
            new_name='user',
        ),
        migrations.AddField(
            model_name='user_stock',
            name='quantity_purchased',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_stock',
            name='gain_loss',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='user_stock',
            name='percent_gain',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='user_stock',
            name='sold_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
