# Generated by Django 2.2.4 on 2021-04-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0002_auto_20210427_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='curr_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
