# Generated by Django 2.2.4 on 2021-04-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=15),
        ),
    ]
